### ISSUE TITLE
support language (locale from request or as parameter)?

### ISSUE THREAD

**Issue by dieuska** [OnroerendErfgoed/skosprovider_getty#16]
only the default language is supported by Getty, but i think there has to be an extra check if there is a LOCALE or  a 'language=' to first search for that language...  (to be checked)

**Comment by koenedaele** [comment]
Since skosprovider_getty is not linked to pyramid in any way, it's not supposed to pay attention to the locale from a request. Normally skosprovider_getty should already support things like:

```python
provider.get_all(language="nl-BE")
```

Choosing which language to pass to skosprovider_getty is up to the calling code (eg. pyramid_skosprovider or Atramhasis)

**Comment by dieuska** [comment]
ok, i understand about LOCALE.
But I think "provider.get_all(language="nl-BE")" is not handled correctly in skosprovider_getty. 
Currently the provider tries to give the labels in the language that is given at initialisation as the default language, after that the default language is used and after that it falls back to english. The language-parameter on the method itself is not yet available I think.

**Comment by koenedaele** [comment]
I see what you mean. Yes, skosprovider_getty should honour the language keyword on certain operations. Falling back to default languages is a good thing, but the user does need to be able to override at certain points.
